services:
  app:
    container_name: json-web
    image: json-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    networks:
      - proxy

networks:
  proxy:
    external: true
