name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: deploy
        uses: fifsky/ssh-action@master
        with:
          args: "-tt"
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          command: ~/front-project-deploy.sh json-web json-formatter
